# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24eb76adce0c3d185a53ff461d181af4a0c7130fc65edb51571e4d78c17d4aa6041505b3962fd6065595f74f3694b0a1c111646c79e30e523834d646a0ad4369

test:
  secret_key_base: 89456bf746357f79319e7198af060ff83b06dfdcc0ea003c6cc1f1b2808ed664410c942b1bdafbd861fd194ed4eb3c8325a4cd67ee82e85821af95cb5a01c301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
